# Generated by Django 6.0.5 on 2026-05-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlantLookup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plant_code", models.CharField(max_length=20, unique=True)),
                ("location_name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["plant_code"],
            },
        ),
        migrations.CreateModel(
            name="EmissionFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FUEL", "Fuel"),
                            ("ELECTRICITY", "Electricity"),
                            ("FLIGHT", "Flight"),
                            ("HOTEL", "Hotel"),
                            ("GROUND", "Ground Transport"),
                            ("PROCUREMENT", "Procurement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sub_type", models.CharField(max_length=100)),
                ("unit", models.CharField(max_length=20)),
                ("factor_kg_co2e", models.FloatField()),
                ("source", models.CharField(default="DEFRA 2023", max_length=100)),
                ("year", models.IntegerField(default=2023)),
            ],
            options={
                "ordering": ["category", "sub_type"],
                "unique_together": {("category", "sub_type", "unit")},
            },
        ),
    ]
