# Generated by Django 6.0.5 on 2026-05-28 12:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("ingestion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmissionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SAP", "SAP"),
                            ("UTILITY", "Utility"),
                            ("TRAVEL", "Corporate Travel"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "scope",
                    models.IntegerField(
                        choices=[(1, "Scope 1"), (2, "Scope 2"), (3, "Scope 3")]
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FUEL", "Fuel"),
                            ("ELECTRICITY", "Electricity"),
                            ("FLIGHT", "Flight"),
                            ("HOTEL", "Hotel"),
                            ("GROUND", "Ground Transport"),
                            ("PROCUREMENT", "Procurement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("activity_date", models.DateField(blank=True, null=True)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("quantity", models.FloatField(blank=True, null=True)),
                ("quantity_unit", models.CharField(blank=True, max_length=50)),
                ("quantity_normalized", models.FloatField(blank=True, null=True)),
                (
                    "quantity_normalized_unit",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("emission_factor", models.FloatField(blank=True, null=True)),
                ("emission_factor_unit", models.CharField(blank=True, max_length=50)),
                ("co2e_kg", models.FloatField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("vendor", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("raw_data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("FLAGGED", "Flagged"),
                        ],
                        default="PENDING_REVIEW",
                        max_length=20,
                    ),
                ),
                ("flag_reason", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("is_edited", models.BooleanField(default=False)),
                ("edit_history", models.JSONField(default=list)),
                ("is_locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ingestion_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="ingestion.ingestionjob",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emission_records",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-activity_date", "-created_at"],
            },
        ),
    ]
